// Access global dataset generated by generate-manifest.js
const paintings = window.paintingsDataset || [];

const gallery = document.getElementById('gallery');
const navLinks = document.querySelectorAll('nav a');
const lightbox = document.getElementById('lightbox');
const lightboxImg = document.getElementById('lightbox-img');
const captionText = document.getElementById('caption');
const closeBtn = document.querySelector('.close');

let currentTheme = 'all';
let filteredImages = [];
let currentIndex = 0;

function renderGallery(filter = 'all') {
    // Clear gallery
    gallery.innerHTML = '';

    // Create column containers
    const colCount = window.innerWidth <= 600 ? 1 : window.innerWidth <= 1100 ? 2 : 3;
    const columns = [];

    for (let c = 0; c < colCount; c++) {
        const col = document.createElement('div');
        col.className = 'gallery-column';
        columns.push(col);
        gallery.appendChild(col);
    }

    filteredImages = filter === 'all'
        ? paintings
        : paintings.filter(p => p.theme === filter);

    // Distribute images into columns (Row-major: Item 0 -> Col 0, Item 1 -> Col 1...)
    filteredImages.forEach((p, index) => {
        const colIndex = index % colCount;

        const item = document.createElement('div');
        item.className = 'gallery-item';
        item.innerHTML = `
            <img src="${p.path}" alt="${p.title}" loading="lazy">
            <div class="overlay">
                <span class="theme">${p.title}</span>
                <span class="date">${p.date}</span>
            </div>
        `;
        item.onclick = () => openLightbox(index);
        columns[colIndex].appendChild(item);
    });
}

// Re-render on resize to adjust column count
window.addEventListener('resize', () => {
    // Debounce or just re-render
    renderGallery(currentTheme);
});



function openLightbox(index) {
    currentIndex = index;
    const p = filteredImages[currentIndex];
    lightbox.style.display = 'flex';
    lightboxImg.src = p.path;
    captionText.innerHTML = `<strong>${p.title}</strong><br><small>${p.date}</small>`;
    document.body.style.overflow = 'hidden';
}

function navigateCarousel(direction) {
    currentIndex += direction;
    if (currentIndex < 0) currentIndex = filteredImages.length - 1;
    if (currentIndex >= filteredImages.length) currentIndex = 0;

    const p = filteredImages[currentIndex];
    // Smooth transition effect
    lightboxImg.style.opacity = 0;
    setTimeout(() => {
        lightboxImg.src = p.path;
        captionText.innerHTML = `<strong>${p.title}</strong><br><small>${p.date}</small>`;
        lightboxImg.style.opacity = 1;
    }, 200);
}

document.querySelector('.prev').onclick = (e) => {
    e.stopPropagation();
    navigateCarousel(-1);
};
document.querySelector('.next').onclick = (e) => {
    e.stopPropagation();
    navigateCarousel(1);
};

// Keyboard navigation
document.addEventListener('keydown', (e) => {
    if (lightbox.style.display === 'flex') {
        if (e.key === 'ArrowLeft') navigateCarousel(-1);
        if (e.key === 'ArrowRight') navigateCarousel(1);
        if (e.key === 'Escape') closeBtn.onclick();
    }
});

closeBtn.onclick = () => {
    lightbox.style.display = 'none';
    document.body.style.overflow = 'auto';
};

lightbox.onclick = (e) => {
    if (e.target === lightbox) {
        lightbox.style.display = 'none';
        document.body.style.overflow = 'auto';
    }
};

navLinks.forEach(link => {
    link.onclick = (e) => {
        e.preventDefault();
        navLinks.forEach(l => l.classList.remove('active'));
        link.classList.add('active');
        currentTheme = link.getAttribute('data-theme');
        renderGallery(currentTheme);
        window.scrollTo({ top: 0, behavior: 'smooth' });
    };
});

// Initial Render
renderGallery();
